### ISSUE TITLE
Internal Server Error beim Aufruf von Events im Backend

### ISSUE THREAD

**Issue by swinde** [kmielke/calendar-extended-bundle#1]
Was ist das Problem?

Attempted to load class "tl_calendar_events_ext" from the global namespace. Did you forget a "use" statement?
Warning: in_array() expects parameter 2 to be array, null given in /kunden/450720_04758/webseiten/werkschule/c4/vendor/contao/core-bundle/src/Resources/contao/library/Contao/System.php on line 169

**Comment by kmielke** [comment]
das diese Version noch total in der Entwicklung ist, und für den Einsatz noch nicht taugt. ;)

**Comment by swinde** [comment]
Sorry ich wollte noch etwas dazu schreiben, hatte aber vorschnell die Nachricht abgesendet.
Das war nur die Ausgabe der Fehlermeldung aus dem Backend.

**Comment by Dancger** [comment]
Habe den Fehler auch gerade im Wartungsmodus entdeckt (Weiterleitung "Internal Server Error" ins Frontend falls ein Kalender angelegt wird).
Ist es erlaubt, nach der ETA zu fragen? ;)
PS: Vielleicht wäre irgendwo ein Hinweis hilfreich, dass die Erweiterung noch nicht stabil läuft.

**Comment by kmielke** [comment]
evtl. beschreibst du mal etwas genauer, was du genau wo für einen Fehler bekommst. Contao Version, Version der Erweiterung und was du wo wie eingestellt hast, wäre auch noch wichtig. ETA?
