### ISSUE TITLE
Feature Request: Anmeldung bzw. Anmeldebestätigung mit identischer Mailadresse für identisches Event

### ISSUE THREAD

**Issue by rokawedes** [kmielke/calendar-extended-bundle#10]
Hallo,

erst einmal vielen Dank für die tolle Erweiterung. Wir nutzen die Funktionalität der Event-Anmeldung ausgiebig auf unserer Vereinsseite.

Allerdings haben wir auch ein regelmäßiges Problemchen mit folgendem Szenario, bei Anmeldung für Kids einfach zu erklären:

1. Person 1 meldet mit seiner Emailadresse sein Kind 1 für ein Event an.
2. Person 1 meldet zu einem anderen Zeitpunkt mit seiner Emailadresse ein Kind 2 für das gleiche Event an (Nachmeldung).

Dann funktioniert der An-/Abmeldelink nicht (zuverlässig), denn in der CalendarLeadsModel.php steht: 

select * from tl_lead lm 
left join tl_lead_data ld1 on lm.id = ld1.pid 
left join tl_lead_data ld2 on ld2.pid = ld1.pid 
where lm.form_id = ? 
and ld1.name = 'eventid' and ld1.value = ? 
and ld2.name = 'email' and ld2.value = ?

Dies prüft ausschließlich auf die Kombination aus Emailadresse und Event um dann den $published zu setzen. Klappt aber bei obigem Szenario nicht.

Es sollte nahezu unmöglich sein, dass sich mit ein und derselben Mailadresse zum exakt gleichen Zeitpunkt jemand anmeldet. Daher ist Idee meinerseits, ein verstecktes Feld "ref" mit Inhalt YmdHis im Anmeldeformular zu setzen und genau diesen Zeitparameter im Anmeldelink mitzugeben:

anmeldung.html?lead=4&event=4&email=invalid@invalid.invalid&ref=20190312105134

Das bedeutet, dass 

1. in ModuleEventRegistration.php compile() die Variable in der ausgewertet werden muss:
$ref = (\Input::get('ref')) ? \Input::get('ref') : false;

2. die Query in CalendarLeadsModel.php angepasst/erweitert werden muss
select * from tl_lead lm 
left join tl_lead_data ld1 on lm.id = ld1.pid 
left join tl_lead_data ld2 on ld2.pid = ld1.pid 
left join tl_lead_data ld3 on ld3.pid = ld2.pid 
where lm.form_id = ? 
and ld1.name = 'eventid' and ld1.value = ? 
and ld2.name = 'email' and ld2.value = ?
and ld3.name = 'ref' and ld3.value = ?

Vielleicht kann man das auch über den bereits vorhanden tstamp-Wert umsetzen, ich habe mir jetzt aber erstmal auf diese Art geholfen.

Könnte dies dauerhaft einfließen?

MfG
Ronny Kämpfe

**Comment by kmielke** [comment]
Ich werde das so nicht umsetzen
