### ISSUE TITLE
Kompatibilität mit der Erweiterung tags

### ISSUE THREAD

**Issue by jankout** [kmielke/calendar-extended-bundle#11]
Hallo, 

ich habe [die Erweiterung tags](https://github.com/hschottm/tags) über den Contao-Manager installiert und leider funktionierte das Anzeigen vom Anmeldeformular danach nicht mehr - es wurde lediglich die Formular-ID ausgegeben. Dieses Fehlverhalten habe ich auch dem anderen Erweiterungsentwickler mitgeteilt. Es wäre schön, wenn beide Erweiterungen nebeneinander funktionieren könnten. Könntest du das bitte überprüfen und ggf. korrigieren? 

Schon jetzt danke ich dir für deine Antwort. 

Liebe Grüße,
Jan

**Comment by kmielke** [comment]
Tags und calendar-extended-bundle sind nicht miteinander kompatible, da jede Erweiterung einen eigenen EventReader mitbringt.

**Comment by jankout** [comment]
OK. Trotzdem besteht der Fehler weiterhin. Warum sollte die Fehlermeldung gleich geschlossen sein? 

Kann man das irgendwie lösen? Ich fände es toll, wenn sich die Erweiterungen nicht gegenseitig ausspielen würden. Das finde ich schade und eigentlich gegen den Sinn der weiteren Contao-Erweiterungen, die miteinander auskommen sollen.
