### ISSUE TITLE
Fehler mit 4.7.4

### ISSUE THREAD

**Issue by jankout** [kmielke/calendar-extended-bundle#12]
Hallo, leider tritt folgender Fehler auf. Contao 4.7.4 Kann ich es irgendwie selber lösen?

`[2019-04-14 10:28:06] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Maximum execution time of 60 seconds exceeded" at /homepages/u2652/www/contao4/vendor/kmielke/calendar-extended-bundle/src/Resources/contao/classes/EventsExt.php line 250 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Maximum execution time of 60 seconds exceeded at /homepages/u2652/www/contao4/vendor/kmielke/calendar-extended-bundle/src/Resources/contao/classes/EventsExt.php:250)"} []`

**Comment by jankout** [comment]
Danke

**Comment by kmielke** [comment]
ich brauche noch deine Einstellungen für das Modul, dass du im FE verwendest. Im BE kommt der Fehler ja nicht.

**Comment by jankout** [comment]
Hier als PDF
[Eventliste vergangene.pdf](https://github.com/kmielke/calendar-extended-bundle/files/3077224/Eventliste.vergangene.pdf)
[Eventliste künftige.pdf](https://github.com/kmielke/calendar-extended-bundle/files/3077225/Eventliste.kunftige.pdf)

**Comment by kmielke** [comment]
in beiden Fällen kommt der Fehler?

**Comment by jankout** [comment]
ja, leider ja.

**Comment by kmielke** [comment]
dann noch PHP Version und die Datum Eingaben aus Einstellungen und aus dem Seitenbaum

**Comment by jankout** [comment]
Hier noch das Template. 

```
<div class="event layout_list<?= $this->classList ?>" itemscope itemtype="http://schema.org/Event">
<?php if ($this->header): ?>
  <div class="header<?= $this->classHeader ?>">
	  <?php if ($this->addImage): ?>
    <?php $this->insert('image', $this->arrData); ?><?php endif; ?>
  <div class="overlay-info">
	  <div class="inside">
    <p class="time"><time datetime="<?= $this->datetime ?>" itemprop="startDate"><?php echo $this->parseDate('d.m.Y', $this->startDate); ?><?php if ($this->endDate): ?> - <?php echo $this->parseDate('d.m.Y', $this->endDate); ?><?php endif ?><?php if ($this->time) echo ' ' . $this->time; ?></time></p>
     <?php if ($this->location || $this->address): ?>
    <p class="location" itemprop="location" itemscope itemtype="http://schema.org/Place">
      <?php if ($this->location_link): ?><a href="<?php echo $this->location_link ?>" target="_blank"><?php endif ?>
      <span itemprop="name"><span class="icon-map-pin"></span><?= $this->location ?></span>
      <?php if ($this->address): ?>
        <span itemprop="address" itemscope itemtype="http://schema.org/PostalAddress"><?= $this->address ?></span>
      <?php endif; ?>
      <?php if ($this->location_link): ?></a><?php endif ?>
    </p>
  <?php endif; ?>
  </div>
  </div>
  </div>
<?php endif; ?>
<?php if ($this->categories): ?>
    <div class="categories">
        <ul>
        <?php
	        $url = 'seminar-filter';
            $cat_ar = deserialize($this->categories, true);
            foreach ($cat_ar as $cat_id) {
                $objCat = Database::getInstance()->prepare("SELECT title FROM tl_mae_event_cat WHERE id = ? LIMIT 1")->execute($cat_id);
                echo '<li><a href="' . $url . '/kategorie/' . strtolower($objCat->title) . '"' . 'title="' . $objCat->title . '">' . $objCat->title . '</a></li>';
            }
        ?>
        </ul>
    </div>
  <?php endif; ?>
  <h2 itemprop="name"><a href="<?= $this->href ?>" title="<?= $this->title ?> (<?php if ($this->day) echo $this->day . ', '; ?><?= $this->date ?><?php if ($this->time) echo ' ' . $this->time; ?>)"<?= $this->target ?> itemprop="url"><?= $this->link ?></a></h2>
   <?php if ($this->hasDetails || $this->teaser): ?>
  <div class="ce_text block teaser" itemprop="description">
      <?php  
      $text= $this->teaser; 
      if (strlen($text) >= 100){ 
          echo strip_tags(substr($text, 0, strpos($text," ",150)))." ...";  
      } else { 
          echo $text; 
      } 
      ?> 
  </div>
  <?php endif; ?>
<?php if ($this->hasDetails): ?>
    <p class="more"><a href="<?= $this->href ?>" title="<?= $this->readMore ?>"<?= $this->target ?> itemprop="url"><span class="icon-arrow-5-right"></span><?= $this->more ?><span class="invisible"><?= $this->link ?></span></a></p>
  <?php endif; ?>
</div>
```

**Comment by kmielke** [comment]
ich kann es bisher nicht reproduzieren.

**Comment by jankout** [comment]
PHP 7.3.4

**Comment by jankout** [comment]
Gestern ging es… Meinst du, dass es am Anbieter liegen könnte?

**Comment by kmielke** [comment]
lol... öhm, wäre eine Überlegung wert, ne? Schau mal, ob du das prüfen kannst. Ich teste es mal mit PHP 7.3.4, habe nämlich aktuell 7.2.17 drauf.

**Comment by jankout** [comment]
Ja, ich schaue mal, ob ich da eine Logdatei finde.

**Comment by jankout** [comment]
Leider kann ich da in den Statistiken nicht sehen bzw. finden - diese sind zuletzt für den 31.3. vorhanden.

**Comment by jankout** [comment]
ich probiere das noch bei einem anderen Anbieter zum Laufen zu bringen. Gleich melde ich mich bei dir.

**Comment by jankout** [comment]
Ich habe es wahrscheinlich herausgefunden. Wenn ein Event vergangen ist und eine Wiederholung dabei steht, kommt es zu diesem Fehler. Bei künftigen passiert es nicht.

**Comment by kmielke** [comment]
hm. vorhin sagtest du, es tritt in beiden Listen auf...

**Comment by jankout** [comment]
ja, leider wurde nichts gezeigt. Erst als ich es bei einem Event herausgenommen habe. 

Noch ein anderes merkwürdiges Verhalten habe ich festgestellt. Sobald 2 Veranstaltungen am selben Tag stattfinden, wird das Bild bei der zweiten nicht geladen, obwohl es da hinzugefügt wurde. Das betrifft auch die sich wiederholenden. Siehe http://dev.esgberlin.de/veranstaltungen

**Comment by kmielke** [comment]
Hallo Jan,
wenn du einen Fehler hast, den du reproduzieren kannst, dann beschreibe so genau wie möglich, wann es genau zu dem Fehler kommt. Du wirst sicherlich Verständnis dafür haben, dass ich mich nicht hinsetze, und versuche das Nachzustellen. Alles was ich in einer Standard-Contao-Installation nicht nachstellen kann, ist für mich erstmal kein Fehler.

Merkwürdiges Verhalten ist keine Fehlerbeschreibung. ;)
Eine weitere Bitte. Ein Ticket für einen Fehler.

**Comment by kmielke** [comment]
Und noch was. Das mit den wöchenlichen Wiederholungen ist ja Standard Contao. Deaktiviere mal calendar-extended-bundle (geht das in der 4 überhaupt noch?), oder versuche es nochmal. Wenn es immer noch auftritt, ist es ein Fehler in Contao.

**Comment by kmielke** [comment]
Ok, habe das ganze mit Standard Contao 4.7.4 und PHP 7.3.4 getestet, und kann es nicht reproduzieren.
