### ISSUE TITLE
?month=201913

### ISSUE THREAD

**Issue by Metis77** [kmielke/calendar-extended-bundle#13]
When your plugin is installed, the calendar month navigation next is broken on each new year.

If viewing december, next should be january of the next year.
Instead it links to ?month=202013, as if there would be a month 13.

I tested this in latest Contao 4.4 and 4.7.
I can offer credentials for testing, if needed.

**Comment by kmielke** [comment]
Danke.
Fixed. Kommt in der nächsten Version.
