### ISSUE TITLE
Unterschiedliche Interpretation Tagesbeginn Contao > FullCalender + Fix

### ISSUE THREAD

**Issue by Metis77** [kmielke/calendar-extended-bundle#15]
Contao versteht den Beginn des Tages als 00:00 Uhr.

FullCalendar sieht das bei Endzeiten etwas anders. 
Endzeiten werden exklusiv der angegebenen Zeit interpretiert.
Somit wird 00:00 im Grunde von FullCalendar als 23:59 interpretiert.

Dadurch werden alle ganztägigen UND mehrtägigen Events einen Tag zu kurz angezeigt.

Fix: 
das hier in `fullCalendar({})`einfügen.
```js
eventDataTransform: function(event) {                 
      if(event.allDay) {             
             event.end = moment(event.end).add(1, 'days')
      }
      return event;  
},
```

Mehr zur besonderen Zeitinterpretation von FullCalendar und dieser Lösung hier:
https://stackoverflow.com/questions/27604359/fullcalendar-event-spanning-all-day-are-one-day-too-short

**Comment by kmielke** [comment]
Danke, habe ich übernommen.
