### ISSUE TITLE
When switching a calendar to another year, an error occurs

### ISSUE THREAD

**Issue by mlwebworker** [kmielke/calendar-extended-bundle#16]
Wenn ich im Kalender über den Jahreswechsel hinaus klicke, dann bekomme ich einen Fehler, weil je nach Blätterrichtung als Parameter folgendes verwendet wird
?month=201813
?month=201900
Das Problem tritt nicht auf wenn der Standardkalender verwendet wird. Es tritt sowohl in Contao 4.4 als auch in Contao 4.7 (jeweils aktuellste Version) auf, PHP-Version 7.2 und auch 7.3. Eine Wechselwirkung mit anderen Erweiterungen kann ich ausschließen, da ich eine Testinstallation nur mit Corefunktionalität aufgebaut habe. Angepasste Templates sind in der Testinstallation definitiv nicht im Einsatz.
Ich kann nicht sagen in welcher Version, der Fehler das erste mal aufgetreten ist (man blättert ja nur manchmal durch den Kalender), meine aber, dass es in der letzten Version ohne Notification Center noch funktioniert hat.

**Comment by kmielke** [comment]
Ist bereits gefixt. Siehe #13. Kommt mit der nächsten Version.

**Comment by mlwebworker** [comment]
Entschuldigung hatte ich übersehen.
