### ISSUE TITLE
Installation in Contao 4.7.6 nicht möglich

### ISSUE THREAD

**Issue by Samson1964** [kmielke/calendar-extended-bundle#17]
Das Bundle läßt sich nicht installieren. Der Cloud Resolver wirfte mir immer denselben Fehler aus:
`
> Resolving dependencies using Composer Cloud v2.0.10
[371.2MiB/5.68s] Loading composer repositories with package information
[371.5MiB/5.79s] Updating dependencies
[2025.7MiB/42.63s] Your requirements could not be resolved to an installable set of packages.
[2025.7MiB/42.63s] 
  Problem 1
    - kmielke/calendar-extended-bundle 1.0.4 requires terminal42/notification_center 1.4.* -> satisfiable by terminal42/notification_center[1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.x-dev] but these conflict with your requirements or minimum-stability.
    - kmielke/calendar-extended-bundle 1.0.3 requires terminal42/notification_center 1.4.* -> satisfiable by terminal42/notification_center[1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.x-dev] but these conflict with your requirements or minimum-stability.
    - kmielke/calendar-extended-bundle 1.0.2 requires terminal42/notification_center 1.4.* -> satisfiable by terminal42/notification_center[1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.x-dev] but these conflict with your requirements or minimum-stability.
    - kmielke/calendar-extended-bundle 1.0.1 requires terminal42/notification_center 1.4.* -> satisfiable by terminal42/notification_center[1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.x-dev] but these conflict with your requirements or minimum-stability.
    - kmielke/calendar-extended-bundle 1.0.0 requires terminal42/notification_center 1.4.* -> satisfiable by terminal42/notification_center[1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.x-dev] but these conflict with your requirements or minimum-stability.
    - Conclusion: don't install kmielke/calendar-extended-bundle 1.0.6
    - Installation request for kmielke/calendar-extended-bundle ^1.0 -> satisfiable by kmielke/calendar-extended-bundle[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6].
    - Conclusion: don't install menatwork/contao-multicolumnwizard 3.3.16
    - kmielke/calendar-extended-bundle 1.0.5 requires menatwork/contao-multicolumnwizard-bundle 3.4.* -> satisfiable by menatwork/contao-multicolumnwizard-bundle[3.4.0, 3.4.1].
    - don't install menatwork/contao-multicolumnwizard-bundle 3.4.0|don't install menatwork/contao-multicolumnwizard 3.3.16
    - don't install menatwork/contao-multicolumnwizard-bundle 3.4.1|don't install menatwork/contao-multicolumnwizard 3.3.16
    - Installation request for menatwork/contao-multicolumnwizard (locked at 3.3.16, required as ^3.3) -> satisfiable by menatwork/contao-multicolumnwizard[3.3.16].
[2025.7MiB/42.63s] <warning>Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.</warning>
[677.6MiB/50.20s] Memory usage: 677.64MB (peak: 2317.1MB), time: 50.2s.
[677.6MiB/50.21s] Finished Composer Cloud resolving.
`

**Comment by kmielke** [comment]
Ich habe es eben in einer Contao Managed installiert.
`Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 12 installs, 0 updates, 0 removals
  - Installing contao-community-alliance/composer-plugin (3.0.9): Downloading (100%)         
  - Installing pimple/pimple (v1.1.1): Loading from cache
  - Installing contao-community-alliance/dependency-container (2.0.3): Loading from cache
  - Installing contao-community-alliance/event-dispatcher (2.0.5): Loading from cache
  - Installing contao-community-alliance/events-contao-bindings (4.4.4): Loading from cache
  - Installing contao-community-alliance/translator (2.1.3): Loading from cache
  - Installing menatwork/contao-multicolumnwizard-bundle (3.4.1): Loading from cache
  - Installing codefog/contao-haste (4.23.4): Downloading (100%)         
  - Installing terminal42/contao-leads (1.4.12): Loading from cache
  - Installing terminal42/dcawizard (2.4.7): Downloading (100%)         
  - Installing terminal42/notification_center (1.5.6): Downloading (100%)         
  - Installing kmielke/calendar-extended-bundle (1.0.6): Downloading (100%)         
codefog/contao-haste suggests installing phpoffice/phpspreadsheet (Required for the Haste\IO\ExcelFileWriter component.)
terminal42/contao-leads suggests installing phpoffice/phpexcel (To enable excel export of lead data.)
Writing lock file
`
Hat wunderbar geklappt.
