### ISSUE TITLE
FR: zus. Auswahl bei "Event wiederholen (erweitert)" für Angabe aller wieviel Monate

### ISSUE THREAD

**Issue by zonky2** [kmielke/calendar-extended-bundle#18]
ich habe jeden ersten Montag im Monat eine Veranstaltung - aber die wiederholt sich erst jeden zweiten Monat; mit anderen Worten: ich habe einen Infoabend und einen Themenabend an dem Montag, aber über die Monate hinweg alternierend.

Bei der Angabe "Event wiederholen (erweitert)" wäre die Angabe "aller wieviel Monate" mit 1 bis 12 prima.

Wenn Du entsprechende Kapazitäten hast, wäre eine Einbau prima und ich könnte das Sponsoren - kurze Rückmeldung wäre prima.

**Comment by kmielke** [comment]
Mache da nichts mehr dran. Sorry
