### ISSUE TITLE
Abhängigkeiten des Bundels vom Core

### ISSUE THREAD

**Issue by mlwebworker** [kmielke/calendar-extended-bundle#2]
Bei Testen ist aufgefallen, dass es beim Deinstallieren der Core-Bundles (Calendar, FAQ ...) und nachträglicher Installation des calendar-extended-bundl zum Fehler kommt.
Kannst Du bitte die composer.json dementsprechend anpassen.

**Comment by kmielke** [comment]
gerne, wenn du mir sagst, was ich anpassen muss. ;)

**Comment by mlwebworker** [comment]
Würde ich gerne tun, aber ich bin kein Entwickler. Ich habe bei Tests für den Contao Manager folgendes Szenario getestet. Alle Core-Bundle deinstalliert und dann u.a. Dein Bundle installiert. Dass führte zum Absturz der Installation. Nachdem Andreas  und Yanick sich die composer.lock angeschaut haben, meinten sie, dass da in Deiner Erweiterung die Abhängigkeiten nicht richtig definiert sind (calendar-extended-bundle wird klaglos installiert, obwohl das benötigte calendar-bundle fehlt) und ich dass doch bitte gleich mal auf Github melden solle.
Ansonsten kann ich nur Andreas oder Yanick bitten mehr Klarheit ins Dunkel zu bringen.

**Comment by kmielke** [comment]
added "contao/calendar-bundle": "^4.4" to composer.json. Hoffe, es passt so. ;)

**Comment by mlwebworker** [comment]
Bin wegen der Konferenz erst heute zum Testen gekommen. Ja das passt jetzt. Danke
