### ISSUE TITLE
Module EventMenu - yearly doens't work

### ISSUE THREAD

**Issue by tarun-uwe** [kmielke/calendar-extended-bundle#21]
Hi kmielke,

the original Contao Template [mod_eventmenu.html5](https://github.com/contao/calendar-bundle/blob/4.8/src/Resources/contao/templates/modules/mod_eventmenu.html5#L5) asks for `$this->yearly` which is not set in the function `protected function compileYearlyMenu()`. 

https://github.com/kmielke/calendar-extended-bundle/blob/0b2a069e72ffdd58bf5223b6d4339128d11e6c8d/src/Resources/contao/modules/ModuleEventMenu.php#L112-L116

In that part, the following line should be added.

`$this->Template->yearly = true;`

Tested in Contao 4.8.4 and 4.4.44.

**Comment by tarun-uwe** [comment]
Backup Info: In your Contao 3 Extension existed a seperated template file.

https://github.com/kmielke/calendar_extended/blob/3.7.x/modules/ModuleEventMenu.php#L77-L83

**Comment by kmielke** [comment]
fixed
