### ISSUE TITLE
Module EventMenu - custom Template doesn't work

### ISSUE THREAD

**Issue by tarun-uwe** [kmielke/calendar-extended-bundle#22]
Hi kmielke,

if you select a custom template, with a different name eg.  _mod_eventmenu_yearly_ then it is not used. 

https://github.com/kmielke/calendar-extended-bundle/blob/d77bffaf40af8d2389b549ba2e4ce0926fcba2ca/src/Resources/contao/modules/ModuleEventMenu.php#L80-L82

That could be fixed with the part from [Module.php](https://github.com/contao/core-bundle/blob/2be4ebc354bd48ca8b3277234e98153565536cf7/src/Resources/contao/modules/Module.php#L143-L146) 

`if ($this->customTpl && TL_MODE == 'FE') {
	$this->strTemplate = $this->customTpl; 
}`

A solution could be: 

```
if ($this->customTpl && TL_MODE == 'FE') { 
  $strTemplate = $this->customTpl; 
} else {
  $strTemplate = 'mod_eventmenu';
} 

/** @var \FrontendTemplate|object $objTemplate */
$objTemplate = new \FrontendTemplate($strTemplate);
```

Tested on Contao 4.8.4

**Comment by kmielke** [comment]
fixed
