### ISSUE TITLE
"Endzeit ignorieren" bei vorhandenen Events ohne Endzeit

### ISSUE THREAD

**Issue by Anke** [kmielke/calendar-extended-bundle#23]
Hallo Kester,

uns ist aufgefallen, dass es nach der Installation von calendar-extended bei schon vorhandenem Eventbestand passiert, dass beim Bearbeiten von Events mit Startzeit automatisch eine Endzeit eingetragen wird. 

Ich weiß, es gibt die Option "Endzeit ignorieren", aber das muss man erst mal checken (wenn man deine Extension noch nicht kennt) und alle Datensätze entsprechend ändern. In unserem Fall wäre es sinnvoll gewesen, wenn die Endzeit defaultmäßig ignoriert würde, was eigentlich auch dem Calendar-Standard entspräche. Andererseits weiß ich nicht, was dann mit Events passieren würde, bei denen eine Endzeit definiert ist. Aber das wäre bestimmt mit einer entsprechneden Abfrage möglich ...?

Gruß,
Anke

**Comment by kmielke** [comment]
Hallo Anke,

was ist jetzt der Fehler?

Gruß Kester

**Comment by Anke** [comment]
> 
> 
> dass beim Bearbeiten von Events mit Startzeit automatisch eine Endzeit eingetragen wird.
Das ist ein Sportverein mit vielen Events, von denen viele eine Anfangs, aber keine Endzeit haben. Der Redakteur hatte über "mehrere Bearbeiten" neue Aliase generieren lassen, und danach hatten alle diese Events auf einmal Endzeiten (startzeit z.B. 10 Uhr, Endzeit dann nächster Tag 09:59), was im FE ausgegeben wurde. 

Wie gesagt, wenn man es weiß, muss man die Datensätze noch einmal bearbeiten und das Kästchen "Endzeit ignorieren" ankreuzen, aber zunächst wussten wir gar nicht, wie es auf einmal zu diesen Endzeiten kam. 

Im Calendar lässt man das Feld Endzeit leer, wenn keine angegeben werden soll. Daher die Frage, ob es sinnvoll wäre, die Option "Endzeit ignorieren" per Default in calendar-extended zu aktivieren.

**Comment by kmielke** [comment]
Hm... das liegt im Auge des Betrachters. Für euch wäre sicherlich hilfreich, für andere nicht. Das Feature ist seit einer Ewigkeit in der Erweiterung, und ihr seid die ersten, die da ein Problem haben. 
Ich denke nicht, dass ich den default ändere. Möglicherweise haben dann viele andere ein Problem, dass ich dann lösen muss.
