### ISSUE TITLE
Unregelmäßige Wiederholungen

### ISSUE THREAD

**Issue by c4y** [kmielke/calendar-extended-bundle#24]
Kann es sein, dass unter 4.9 die unregelmäßigen Wiederholungen nicht funktionieren? Es findet bei mir keine Wiederholung statt

**Comment by kmielke** [comment]
Wenn du einen echten Fehler hast, dann melde den mit Fehlermeldung. Mit deiner Aussage kann ich rein gar nichts anfangen. Und ins blaue hinein suchen, ohne dein Konstellation zu kennen, werde ich sicherlich nicht. ;)
