### ISSUE TITLE
CSS-Klasse im Event wird von ModuleEventlist.php berschrieben

### ISSUE THREAD

**Issue by SFachinger** [kmielke/calendar-extended-bundle#25]
Kann es sein, dass durch die ModuleEventlist.php die im Ebent vergebene CSS-Klasse überschrieben wird (Zeile 311)

Es kommt in der Listensansicht des Event nur die Klasse "regopen" an.

Danke
Steffen

**Comment by kmielke** [comment]
Ist das jetzt eine Vermutung, oder hast du konkret einen Fehler, den du dokumentieren kannst?
Wenn du was konkretes hast, kannst du den Bug gerne wieder auf machen. Ich werde mich jetzt nicht hinsetzen, und deine Vermutung untersuchen, ohne konkrete Hinweise. 😉

**Comment by SFachinger** [comment]
Moin Kester,

ich bin keiner, der nur nach Fehlern sucht. 😉

Sobald in einem Event die der Punkt "Anmeldung" angehakt wird, kommt die CSS-Klasse aus den Einstellungen des Events nicht mehr durch.

Kannst Du Dir auf der Testinstallation unter
[c49.kreuzbund-dv-limburg.de](url) 
ansehen. Ganz unten in der linken Spalte findest Du die Boxen mit den Terminen. Diesen habe ich alle die CSS-Klasse "abgesagt" mitgegeben. Bei den grünen Boxen (=mit Anmeldung) kommt als CSS nur 
`<div class="event Seminare layout_upcoming regopen even cal_11">`

Bi den events OHNE Anmeldung kommt:
`<div class="event Kreuzbund Termine layout_upcoming abgesagt upcoming odd cal_8">`

Bei der genaueren Untersuchung bin ich dann auf die Zeile 311 in der ModuleEventlist.php gest0ßen, in der nach meinem (begrenzten) Verständnis der Inhalt von "class" ersetzt, statt ergänzt wird.

**Comment by kmielke** [comment]
Dann gib mir mal mehr Info's. Contao Version, und Version der Erweiterung.

**Comment by SFachinger** [comment]
Contao 4.9.2
kmielke/calendar-extended-bundle: 1.0.8

Brauchst Du noch sonstige Infos?

**Comment by kmielke** [comment]
fixed
