### ISSUE TITLE
Event Booking funktioniert bei Installation der Extension "rel-canonical" nicht

### ISSUE THREAD

**Issue by chriza** [kmielke/calendar-extended-bundle#26]
Contao 4.9.3
kmielke/calendar-extended-bundle 1.0.9
christianbarkowsky/rel-canonical 3.3.9

Hallo,
ich habe in einer frischen Testumgebung ohne rel-canonical eine Event-Buchung realisiert. Alles ok.
Danach habe ich rel-canonical installiert. Auswirkung: in die Variable regform wird die ID des Buchungsformulares statt dessen Inhalt eingefügt.

Gibt es ein zeitlich vertretbare Lösung dieses Problemes?

**Comment by kmielke** [comment]
Hallo chriza,

als Fehlerbeschreibung reicht das nicht aus. Ich bin auch nur kompatibel zum Contao Standard, und nicht zu allen möglichen Erweiterungen. Wenn du ein echten Fehler in meiner Erweiterung dokumentieren kannst, schaue ich mir das an. Sonst werde ich da keine Arbeit rein stecken.

**Comment by chriza** [comment]
Hallo,
die Situation läßt sich leicht nachstellen: In eine bestehende calendar-extended-bundle Installation mit Buchungsformular die Extension rel-canonical nachinstallieren. Das Buchungsformular wird nicht mehr ausgeliefert werden.
