### ISSUE TITLE
Notification center 1.5.*

### ISSUE THREAD

**Issue by chibko** [kmielke/calendar-extended-bundle#28]
Hello,

I have a Contao 4.9.4 installed with Isotope 2.6.13. Impossible to install your bundle.

Isotope requires :
- contao-multicolumnwizard 3.2
- Notification center 1.5

And your bundle in 1.04
- contao-multicolumnwizard 3.2
- Notification center 1.4

And your bundle in 1.10
- contao-multicolumnwizard-bundle 3.4
- Notification center 1.5

**Comment by kmielke** [comment]
Please Look at the Closeup bugs and habe a look at the forum too. 
Thx 😉

**Comment by mathContao** [comment]
if somebody will come here by google: this is the mentioned bug: https://github.com/kmielke/calendar-extended-bundle/issues/27
