### ISSUE TITLE
warning: problem when requiring fullcalendar/fullcalendar

### ISSUE THREAD

**Issue by fritzmg** [kmielke/calendar-extended-bundle#3]
Currently you require `fullcalendar/fullcalendar`. This may cause problems in certain Contao 4 installations. Since `fullcalendar/fullcalendar` also requires `components/jquery` and since Contao 4 previously used
```
"config": {
    "component-dir": "assets"
}
```
in the root `composer.json`, `components/jquery` will also get installed into `assets/` and thus may delete and overwrite `contao-components/jquery`, breaking the JavaScript of the Contao installation, if jQuery is enabled in the page layout, since the path to jQuery will not be in the expected one (and the version will automatically bump from 1.x to 3.x).

To fix this, users have to delete
```
"config": {
    "component-dir": "assets"
}
```
from their root `composer.json` and instead add
```
"extra": {
    "contao-component-dir": "assets"
}
```
This will install `contao-components/jquery` into `assets/` and `components/jquery` into `components/`.

See also https://community.contao.org/de/showthread.php?71651-Nach-Update-auf-4-4-21-wird-jquery-nicht-mehr-lokal-geladen-nur-CDN

**Comment by kmielke** [comment]
Problem ist behoben. Neue Version steht zur Verfügung. Danke für das Feedback.
