### ISSUE TITLE
xhtml templates

### ISSUE THREAD

**Issue by mathContao** [kmielke/calendar-extended-bundle#31]
Ich denke, dass die xhtml-Templates gelöscht werden können, da sie nicht mehr benötigt werden. Seit Contao 4.0 werden nur noch html5-Templates genutzt (siehe https://www.mittwald.de/blog/cms/contao/die-neuerungen-von-contao-4-0)

![grafik](https://user-images.githubusercontent.com/1645099/89330687-edb63f00-d690-11ea-9bf9-4def9da6bde5.png)

**Comment by kmielke** [comment]
Es ist möglich, dass diese nicht mehr benötigt werden. Evtl. erfolgt mal eine Bereinigung. ;)
