### ISSUE TITLE
evr_registration.html5: $this>msg immer leer

### ISSUE THREAD

**Issue by mathContao** [kmielke/calendar-extended-bundle#32]
Wenn ich das richtig überschaue wird die Variable $this->msg im Template evr_registration.html5 immer leer bleiben:

![grafik](https://user-images.githubusercontent.com/1645099/89332563-e47aa180-d693-11ea-84f4-1cdae8bd6cdb.png)

**Comment by kmielke** [comment]
hm... da ich nicht weiß, was du alles wie überschaut hast, und ich hier keinen Fehler sehe, mache ich das Ticket wieder zu. Wenn du einen richtigen Fehler hast, und den auch gut beschreiben kannst, habe ich was, dass ich mir anschauen kann.

**Comment by mathContao** [comment]
ich habe alle Dateien in diesem Repository nach dem String "msg" durchsucht.

der Ordner "calendar-extended-bundle-master" (das ist die entzippte Datei, die man hier bei Github herunterladen kann) wurde dabei durchsucht.

Ich kann keine Stelle im Quellcode finden, die die msg-Variable befüllt.
