### ISSUE TITLE
$this->reginfo['free'] negativ

### ISSUE THREAD

**Issue by mathContao** [kmielke/calendar-extended-bundle#35]
Wird die zulässige Teilnehmerzahl nachträglich niedriger als die bereits angemeldete Teilnehmerzahl geändert, dann wird eine negative Zahl mit der Template-Ausgabe `$this->reginfo['free']` erzeugt.

Template:
![grafik](https://user-images.githubusercontent.com/1645099/89707463-69084100-d96e-11ea-9451-70569f233f7c.png)

Ausgabe:
![grafik](https://user-images.githubusercontent.com/1645099/89707484-b4baea80-d96e-11ea-836d-21f967af14c2.png)

Erwartet hätte ich eine 0, egal wie negativ die Zahl eigentlich mathematisch wäre.

**Comment by kmielke** [comment]
Das kann man schön im Template abfangen, und mit einem zusätlichen Text versehen, dass das Event überbucht ist. ;)
