### ISSUE TITLE
Liste der Anmeldeformulare alphabetisch sortieren

### ISSUE THREAD

**Issue by mathContao** [kmielke/calendar-extended-bundle#36]
Ich wünsche mir, dass die Formulare in der Auswahlliste alphabetisch (und nicht nach ID sortiert) aufgelistet werden

![grafik](https://user-images.githubusercontent.com/1645099/90068911-c21b0080-dcf1-11ea-8218-7d64051ebe24.png)

**Comment by kmielke** [comment]
werde ich nicht machen.
