### ISSUE TITLE
Wiederholungen (unregelmäßig) für alle Weiterleitungsziele

### ISSUE THREAD

**Issue by c4y** [kmielke/calendar-extended-bundle#37]
Derzeit können unregelmäßige Wiederholungen nur für das Standard Weiterleitungsziel definiert werden. Schön wäre es, wenn dies auch für die anderen (Seite, Artikel, individuelle URL) gehen würde.

**Comment by kmielke** [comment]
Akktuell wird es keine neuen Features geben.
