### ISSUE TITLE
Änderung bei unregelmässigen Wiederholungen

### ISSUE THREAD

**Issue by Velste** [kmielke/calendar-extended-bundle#38]
Hallöchen, 
ich nutze die Kalender Extension seit einigen Jahren. Seit Neuestem kann ich allerdings keine Weiterleitungen mehr auf Seiten haben, wenn ich unregelmässige Wiederholungen eintragen möchte. Das ist sehr schade, da wir uns die Extension wegen genau diesem Feature zugelegt haben und das so lange erfolgreich genutzt haben. 
Warum gibt es das Feature nicht mehr und dürfen wir damit rechnen, dass es wieder eingeführt wird?
MfG

**Comment by kmielke** [comment]
Hallo,
wenn du einen Fehler melden willst, dann beschreibe den Fehler so genau wie möglich. Schreibe, was du wie machst, und was du erwartest. Welche Version von Contao und von der Erweiterung ist im Einsatz. Ohne genaue Angaben mache ich nichts.
Gruß

**Comment by Velste** [comment]
Ok:
ich benutze Contao 4.9 und die Extension kmielke/calendar-extended-bundle 1.0
Wir bestücken damit den Kalender: http://studioluxberlin.de/kalender.html
Die Einträge linken dann direkt auf die Profilseiten der anwesenden Person. 
Vor dem Corona Lockdown konnte Einträge anlegen, die auf die Seite weiterleiten und gleichzeitig unregelmässige Wiederholungen eingeben. Das war sehr praktisch, denn so musste ich für jedes Teammitglied nur einmal einen Event eintragen und sämtliche Anwesenheitstage als unregelmässige Wiederholungen anlegen. 
Während des Lockdowns haben wir unser Contao einem Update unterzogen (auf 4.9) und wohl auch die neueste Calender Extension Bundle Version. 
Nun geht das nicht mehr, wenn ich den Eintrag auf eine Seite weiterleiten lasse. Ich muss also für jeden Anwesenheitstag einen neuen Eintrag anlegen. 
Die unregelmässigen Wiederholungen sind hier beschrieben:
https://de.contaowiki.org/Calendar_extended#Wiederholungen_unregelm.C3.A4.C3.9Fig

Reicht das als Beschreibung oder soll ich noch ein paar Screenshots anfertigen?

Danke sehr.

LG

**Comment by kmielke** [comment]
Entschuldige, ich habe mich zu ungenau ausgedrückt. Beschreibe, was du innerhalb des Contao machst, also wo setzt du welchen Wert usw... Ich muss es ja in meiner Contao Instanz reproduzieren können. Wenn du dir nicht sicher bist, welche Version du im Einsatz hast, dann musst du das prüfen.

**Comment by Velste** [comment]
Der Einfachheit halber hab ichs mal mit Vide dokumentiert:
http://studioluxberlin.de/preview.php/testseite.html
Einfach auf Video klicken.

**Comment by kmielke** [comment]
geht nicht

**Comment by Velste** [comment]
Mist. 
Ok: Ich klicke links im dashboard auf Event, dann komm ich zur Übersicht der Kalender. Dort wähle ich Event aus und unsere Kalendereinträge öffnen sich.
Ich nehme einen existierenden Event (oder lege einen neu an, ght bei beiden nicht) und kopiere ihn. Die Eventseite öffnet sich. Ich lösche das (Kopie) hinter dem Eventnamen weg. Nun trage ich ein Startdatum mittels des Datumswählers ein. 
Als Weiterleitungsziel wähle ich "Seite" und die entsprechende Seite aus (ich will ja, dass man beim draufklicken auf den Eevent Alias in der Frontendansicht auf die entsprechende Seite kommt.
Nun sehe ich zwar "Wiederholungen", ich kann aber nur regelmässige Wiederholungen eingeben.

Wähle ich als Weiterleitungsziel "Standard", dann habe ich die Auswahl zwischen "Wiederholungen", "Wiederholungen (erweitert)" und "Wiederholungen (unregelmässig)". 
Diese Möglichkeiten hatte ich vor dem Update auch, wenn ich als Weiterleitungsziel "Seite" ausgewählt habe. 

Ich habe laut Contao manager Contao 4.9 im Einsatz und die Extension 1.0 Falls ich sonst noch Werte liefern soll, nur her damit, Screenshots geht auch.

**Comment by Velste** [comment]
![screen01](https://user-images.githubusercontent.com/69849267/90512512-8ef7c780-e15e-11ea-915a-1c24ad297b5e.JPG)
![screen02](https://user-images.githubusercontent.com/69849267/90512516-9028f480-e15e-11ea-9b4f-92d5ba5ae898.JPG)

**Comment by Velste** [comment]
![screen03](https://user-images.githubusercontent.com/69849267/90512861-18a79500-e15f-11ea-960a-cf0c11f5aa19.JPG)
![screen04](https://user-images.githubusercontent.com/69849267/90512863-19402b80-e15f-11ea-8f2a-0552862e9858.JPG)

**Comment by kmielke** [comment]
Habe es verstanden. Aktuelle Version ist 1.0.10

**Comment by Velste** [comment]
Dann mach ich mal ein update und berichte!

**Comment by Velste** [comment]
Habe nun die aktuelle Version, Problem bleibt bestehen. :(

**Comment by kmielke** [comment]
Fixt in Version 1.0.11

**Comment by Velste** [comment]
Daaaaaaaaaaaaaaaaaaaaanke!
