### ISSUE TITLE
Invalid date "20.10.2018 14:00"

### ISSUE THREAD

**Issue by srhinow** [kmielke/calendar-extended-bundle#4]
unter Contao 4.4.26 und PHP 7.2 erscheint der Fehler:
```
in vendor/kmielke/calendar-extended-bundle/src/Resources/contao/classes/EventsExt.php (line 423) 
 $newDateStart = new Date(trim($strNewDate . ' ' . $strNewTime), \Config::get('datimFormat'));
```
Ich denke das man dort erst nen Timestamp draus machen sollte, bevor man das Datum neu formatiert. evtl mit strtotime()
`$newDateStart = new Date(strtotime($strNewDate . ' ' . $strNewTime), \Config::get('datimFormat'));`

**Comment by kmielke** [comment]
Danke. ist gefixt, und kommt mit der nächsten Version.
