### ISSUE TITLE
Kalender unregelmässige Wiederholungen bei Weiterleitungsziel Seite 

### ISSUE THREAD

**Issue by Velste** [kmielke/calendar-extended-bundle#40]
Hallo,
ich habe jetzt explizit die Version 1.0.11 installiert.
Leider kann ich immer noch keine unregelmässigen Wiederholungen anlegen, wenn als Weiterleitungsziel des Kalendertages Seite angelegt ist, statt Standard. 

![kalender01](https://user-images.githubusercontent.com/69849267/90754927-d1deaa00-e2da-11ea-861a-3c959e3aa777.JPG)
![kalender02](https://user-images.githubusercontent.com/69849267/90754929-d2774080-e2da-11ea-82da-5d62eece21f4.JPG)

**Comment by kmielke** [comment]
Cache löschen? Ght bei mir in einer Standard Contao Installation.

<img width="1191" alt="Bildschirmfoto 2020-08-20 um 12 01 11" src="https://user-images.githubusercontent.com/1644959/90756597-dd32d500-e2dc-11ea-8ed8-1bfc61ecde77.png">

**Comment by Velste** [comment]
Hmm, ich habs mich mal aufm Laptop mittels VPN eingeloggt und einen anderen Browser benutzt und krieg es immer noch nicht angezeigt...
