### ISSUE TITLE
"Event wiederholen" & "Event wiederholen (erweitert)" "idiotensicher" machen

### ISSUE THREAD

**Issue by madmaharaja** [kmielke/calendar-extended-bundle#43]
Wir verwenden diese Erweiterung gerne seit vielen Jahren. Eine Fehlerquelle, die aber leider immer wieder auftaucht, ist dass es überhaupt möglich ist "Event wiederholen" und "Event wiederholen (erweitert)" gleichzeitig im Backend anzuwählen. 
Was seit geraumer Zeit schonmal eine Verbesserung dahingehend ist, ist dass ein Alert beim Speichern kommt, wenn beides gleichzeitig angewählt ist ("Es kann nur eine der Optionen für die Wiederholungen aktiv sein."). Nichtsdestotrotz, wenn ein Redakteur die Fehlermeldung ignoriert oder unbewusst einfach auf den Zurück-Button klickt oder sonstwohin in Contao navigiert, dann wird trotzdem die falsche Konfiguration so gespeichert. Zumindest führt das bei uns nicht (mehr) zu einer Fehlermeldung im Frontend, aber der betreffende Event wird dafür jetzt gar nicht mehr im Frontend angezeigt.

Gibt es hierfür nicht eine narrensichere Lösung? Z.B., anstelle von "Event wiederholen" und "Event wiederholen (erweitert)" mit zwei Checkboxen (wie derzeit) parallel anwählbar zu machen, dass sie stattdessen mit Radiobuttons oder einem Selectmenü auszuwählen sind? Also, so, dass wenn ich das eine anwähle, die anderen Optionen automatisch ausgeblendet werden bzw. deaktiviert sind. Vielleicht gibt es ja noch andere, bessere Wege dafür. Jedenfalls scheint mir dies eine vermeidbare Fehlerquelle zu sein.

**Comment by kmielke** [comment]
Aktuell werde ich nicht daran arbeiten. Ich lasse das Ticket mal offen, aber es wird sicherlich erstmal nichts passieren.

**Comment by kmielke** [comment]
Mache da nichts mehr dran. Sorry
