### ISSUE TITLE
ErrorException nur im Debug Mode

### ISSUE THREAD

**Issue by raberos** [kmielke/calendar-extended-bundle#45]
Ich habe Contao 4.10.7 und calendar-extended-bundle 1.0.13. Immer, wenn ich im Debug Modus bin schmeisst es mir eine ErrorException.
![Warning_ Declaration of Kmielke_CalendarExtendedBundle_EventsExt__getAllEvents($](https://user-images.githubusercontent.com/84036473/117857098-b2cee080-b28c-11eb-882b-ac02f1e46569.jpg)
Wenn ich nun die Line 62 von EventsExt.php ändere, funktionierts wieder:
 protected function getAllEvents($arrCalendars, $intStart, $intEnd**, $blnFeatured = NULL**)
Den DebugModus aktiviere ich, indem ich das web/../.env auf 'APP_ENV=dev' ändere.

**Comment by rabauss** [comment]
Should be fixed in the current version - since #57
