### ISSUE TITLE
Im FE Template "event_full" wird "Ausnahmen nach Datum" nur auf Uhrzeit aber nicht auf Datum angewendet

### ISSUE THREAD

**Issue by knollraf** [kmielke/calendar-extended-bundle#47]
Wollte im FE eine Auflistung eines wöchentlichen Termins ausgeben lassen, der an einem Tag ausfällt und um x-Tage mit neuer Startzeit verschoben wird. Hierfür habe ich die Option "Ausnahmen nach Datum" verwendet.

Wenn im FE "exceptionList" ausgegeben wird, wird die Ausnahme mit neuer Startzeit und zu verschiebenden Tagen korrekt erkannt.
Bsp: ein Termin am 23.07. soll um 4 Tage verschoben werden und um 16:30Uhr beginnen:
    [1627022040] => Array
        (
            [exception] => 1627022040
            [new_start] => 16:30
            [new_end] => 
            [action] => move
            [new_exception] => 4 days
            [cssclass] => test_zwei
            [reason] => Kindergeburtstag
            [exception_date] => 23.07.2021 08:34
        )
Im Anschluss soll "repeatDates" ausgegeben werden, wobei hier lediglich die Startzeit aber nicht das Datum des verschobenen Termins korrekt ausgegeben wird.
Array
(
    [1626417240] => 16.07.2021 08:30
    **[1627022040] => 23.07.2021 _16:30_**
    [1627626840] => 30.07.2021 08:30
    [1628231640] => 06.08.2021 08:30
    [1628836440] => 13.08.2021 08:30
    [1629441240] => 20.08.2021 08:30
    [1630046040] => 27.08.2021 08:30
    [1630650840] => 03.09.2021 08:30
    [1631255640] => 10.09.2021 08:30
)

Kann man das Datum noch anpassen?

**Comment by wiphi** [comment]
Ich kann das Problem bestätigen und habe auch schon versucht das Problem zu debuggen. Bislang doch ohne Erfolg. 
Vielleicht kann @kmielke noch einen Tipp geben, an welcher Stelle man suchen könnte.

**Comment by wiphi** [comment]
@knollraf Kannst du mal meinen Branch testen, ob damit das Problem behoben wird: 
https://github.com/wiphi/calendar-extended-bundle/tree/fix-exception-periode
Entsprechende Events müssen ggf. nochmal abgespeichert werden.

**Comment by knollraf** [comment]
@wiphi Habe eben deinen Branch getestet. Allerdings haben die Änderungen bei diesem Thema keine Auswirkung gehabt (?)
Für mich sieht es so aus als wäre $dateToSave und $dateToSaveEnd ab ca. Zeile 1025 falsch zusammengesetzt.

Evtl. muss es mehr in diese Richtung gehen:
$dateToSave = strtotime($row['new_exception']. ', ' . date("d.m.Y", $row['exception']) . ' ' . $row['new_start']);
$dateToSaveEnd = strtotime($row['new_exception']. ', ' . date("d.m.Y", $row['exception']) . ' ' . $row['new_end']);

Bin momentan selber noch am rumtüfteln aber bei mir korrigiert sich das Datum dann um die korrekten Tage. 
z.B. "+ 3 days".

**Comment by wiphi** [comment]
@knollraf Ich habe das soeben durchgetestet und bei mir gehts. Bei mir sehen die Zeilen 1025 so aus:
```php
    $dateToFind = strtotime(date("d.m.Y", $row['exception']) . ' ' . date("H:i", $dc->activeRecord->startTime));
    $dateToSave = strtotime(date("d.m.Y", $row['exception']) . ' ' . $row['new_start']);
    $dateToSaveEnd = strtotime(date("d.m.Y", $row['exception']) . ' ' . $row['new_end']);
```
Ist auch im master-Branch so hinterlegt:
https://github.com/kmielke/calendar-extended-bundle/blob/f5de73d959cb364c4a1a407c66bceea268156912/src/Resources/contao/dca/tl_calendar_events.php#L1017-L1019

Verwendest du ggf eine alte Version?

**Comment by knollraf** [comment]
Hey, erstmal Danke für die schnellen Antworten.
Ja, habe die aktuelle Version vom Masterbranch --> V1.0.14 (veröffentlicht am 10. August 2021 um 11:37).  
Und momentan teste ich es unter Contao V4.9.20.

Habe es eben noch mal überprüft. Mit dem Eventleser-Modul und dem Template "full_event" werden die veränderten Termine trotzdem nur mit der korrekt veränderten Start- und Endzeit angegeben aber nicht mit dem veränderten Datum.
Dafür war mein Lösungsansatz oben gedacht. (Die Zeilenangaben hatte ich von deinem Branch übernommen.)
--> Wenn ich die beiden Zeilen von mir ab Zeile 1037 im Masterbranch vor "// Find the date and replace it" einfüge funktioniert es. Musste allerdings erneut den Termin abspeichern.

Das Kalender-Modul funktioniert bspw. so wie es soll, nur beim Eventleser gibt es das Problem. 
Kannst du es noch mal gegenchecken ob das bei dir auch der Fall ist? 
Vielen Dank im Voraus.

**Comment by wiphi** [comment]
Jetzt hab ich dein Problem verstanden. Ich glaube da ist mehr zu tun...
https://github.com/kmielke/calendar-extended-bundle/blob/f5de73d959cb364c4a1a407c66bceea268156912/src/Resources/contao/dca/tl_calendar_events.php#L1040 
Müsste meiner Meinung `$dateToFind` erst aus dem Array `$arrAllRecurrences` entfernt werden, da das das alte Datum ist. Anschließend das Verschiebe-Datum neu in das Array aufnehmen. 
Ich hab diese Woche leider keine Zeit das zu debuggen, vielleicht klappt es am Wochenende. Vielleicht kann @kmielke was dazu sagen, wie das gedacht ist.

**Comment by wiphi** [comment]
> Habe es eben noch mal überprüft. Mit dem Eventleser-Modul und dem Template "full_event" werden die veränderten Termine trotzdem nur mit der korrekt veränderten Start- und Endzeit angegeben aber nicht mit dem veränderten Datum.

Ich kann das Problem derzeit nicht reproduzieren... Ich habe das ganze mal in der Contao-Demo durchgespielt.
Hier mal ein paar Screenshots zur Verdeutlichung anhand des **Contao NRW-Day**:
Die Einstellung für die Ausnahme im Backend:
<img width="767" alt="2021-09-18 21_28_51-Events Events Event ID 8 bearbeiten _ contao4-9-test vm" src="https://user-images.githubusercontent.com/25878910/133906554-88fe87db-a7c0-4b25-afa4-39d005096ac3.png">
In der Liste im Frontend:
<img width="242" alt="2021-09-18 21_29_34-Events - Contao Official Demo" src="https://user-images.githubusercontent.com/25878910/133906557-98696725-45cf-46e0-bfaf-612e8b1709d0.png">
Ausgabe im Event-Leser mit aktivem event_full Template:
<img width="474" alt="2021-09-18 21_30_03-The Contao NRW-Day - Contao Official Demo" src="https://user-images.githubusercontent.com/25878910/133906558-5c13a938-8a79-4cd6-8b3b-a9ec565a072f.png">
Einstellung des Lese-Moduls:
<img width="657" alt="2021-09-18 21_31_16-Artikel Event Detail Inhaltselemente Inhaltselement ID 313 bearbeiten _ contao4-" src="https://user-images.githubusercontent.com/25878910/133906559-e594286b-029c-4fa7-825f-be217ab4ea94.png">
