### ISSUE TITLE
Automatische sortierung verhindern

### ISSUE THREAD

**Issue by akroii** [kmielke/calendar-extended-bundle#49]
Hallo,
aktuell werden unregelmäßige Wiederholungen mit dem speichern wie folgt sortiert:
<img width="362" alt="Bildschirmfoto 2021-09-04 um 22 18 19" src="https://user-images.githubusercontent.com/8830861/132107100-198965d7-4a11-45ac-a114-f42311a47af7.png">
Es sollte an meinem Beispiel eigentlich so sein, dass zuerst der 19.11., dann der 20.11 und anschließend der 21.11 erscheint.
Die individuelle Sortierung scheint an dieser Stelle defekt zu sein.

Wenn man versucht diese anders zu sortieren und speichern drückt, wird der Urspungszustand (siehe Foto) wieder hergestellt.
Kann man das beheben?

Contao: 4.9.20
kmielke/calendar-extended-bundle:  1.0.14

**Comment by wiphi** [comment]
Ich habe für issue #47 einen Branch erstellt und mir das Problem hier auch gleich mit angeschaut.
Kannst du dir mal diesen Branch https://github.com/wiphi/calendar-extended-bundle/tree/fix-exception-periode auschecken und schauen, ob das dein Problem behebt und die unregelmäßigen Wiederholungen auch noch korrekt bei dir funktionieren?

**Comment by akroii** [comment]
Funktioniert! Unregelmäßige Wiederholungen werden nicht mehr defekt dargestellt
