### ISSUE TITLE
Feature Request: Hinterlegung eines Standard-Veranstaltungsorts im Event-Archive

### ISSUE THREAD

**Issue by ff1601com** [kmielke/calendar-extended-bundle#5]
Guten Tag,
wir verwenden Ihre Erweiterung `kmielke/calendar-extended-bundle` aktiv bei einem unserer Projekte und stießen dabei auf ein noch fehlendes Feature, welches wir uns wünschen würden.

Zu unserem Anliegen: 
Wir benötigen die Möglichkeit einen Standard-Veranstaltungsort im (übergeordneten) Event-Archiv zu hinterlegen, welcher verwendet wird, sofern nicht bei einzelnen Events ein davon abweichender Veranstaltungsort hinterlegt wird.

![image](https://user-images.githubusercontent.com/40162179/49018034-99a04b00-f18a-11e8-9437-132395bdfdb0.png)

**Comment by kmielke** [comment]
Hallo,
ich werde das aus zeitgründen aktuell nicht machen.
Gruß Kester
