### ISSUE TITLE
event-register.js wird geladen, obwohl nicht gebraucht

### ISSUE THREAD

**Issue by manjarco** [kmielke/calendar-extended-bundle#51]
Moin,
ich setzte die Registrierungsfunktion nicht ein, trotzdem wird wohl event-register.js geladen und schmeißt dann einen Fehler:

Uncaught ReferenceError: $ is not defined

Brauchts die Datei überhaupt? Scheint ja nur was in den Console-log zu schreiben…

**Comment by kmielke** [comment]
Gedacht war die Datei auch für eigenen Code, den man dann dort evtl. plazieren will/kann. Da ich nicht weiß, ob jemand diese Datei für eigene Zwecke doch benutzt, lasse ich es so, bzw. mache die Datei leer.
