### ISSUE TITLE
Checkbox "Hervorgehobene Events überspringen" not working

### ISSUE THREAD

**Issue by Ernestopheles** [kmielke/calendar-extended-bundle#63]
![DeepinBildschirmfoto_Bereich auswählen_20220617204859](https://user-images.githubusercontent.com/7561403/174653059-8372933c-92c9-492c-925a-ebbfecd0ab6a.png)
Having checked "Hervorgehobene Events überspringen" I would expect only "Nicht-Hervorgehobene" should be listet. But all events are listed.

**Comment by lennier83** [comment]
Kann ich bestätigen mit Contao 4.11+ und neueste Calender-extendet Version.
Da die Extension offiziell nur für 4.4 ist und Hervorheben erst seit Contao 4.10 verfügbar ist, gibt es sicher noch Funktionen die nicht implementiert sind. Mich wundert nur das diese Extension soviel Einfluss auf neuere Core sachen hat :-)

**Comment by kmielke** [comment]
Ja, aktuell wird hier nichts weiter gemacht. Dieses Feature ist nicht vorhanden. Sorry

**Comment by Ernestopheles** [comment]
Danke für die Info. Ich kann schlecht nachvollziehen warum man Features die Implementiert sind aber fehlerhaft so lassen will. Ehrlich wäre m.E. das Feature dann zu entfernen

**Comment by kmielke** [comment]
Von welchem Feature sprichst? "Hervorgehobene Event"? Das Feature ist Contao selbst, und nicht von meiner Erweiterung. Das kann ich nicht entfernen. ;)

**Comment by Ernestopheles** [comment]
Das Feature wird durch deine Erweiterung fehlerhaft

**Comment by kmielke** [comment]
Tja, dann wirst du wohl die Erweiterung entfernen müssen. Ist nicht mehr kompatible. ;)
Weiterhin viel Erfolg
