### ISSUE TITLE
Voraussetzung für Notification Center stimmen nicht

### ISSUE THREAD

**Issue by jankout** [kmielke/calendar-extended-bundle#7]
Hallo, 

leider kann ich deine tolle Erweiterung nicht installieren, weil da eine Voraussetzung für Notification Center 1.4 steht. Mittlerweile gibt es aber schon die Version 1.5.x. Könntest du bitte diese Restriktion aufheben bzw. erhöhen? Danke. Siehe https://github.com/kmielke/calendar-extended-bundle/pull/8

**Comment by kmielke** [comment]
Ohne das getestet, werde ich das nicht ändern, sorry.

**Comment by jankout** [comment]
Klar, das verstehe ich. Nur die Einschränkung besteht weiter, wenn ich das mit 4.6.x und Notification Center 1.5.x installieren möchte. Ich würde meine Meldung offen lassen, gelöst ist es noch nicht. ;-)

**Comment by fritzmg** [comment]
@kmielke mit Semantic Versioning kannst du prinzipiell davon ausgehen, dass es keine Probleme geben _sollte_.

**Comment by fritzmg** [comment]
Du schreibst ja auch
```
"contao/core-bundle": "^4.4",
```
und nicht
```
"contao/core-bundle": "4.4.*",
```
Es macht imho keinen Sinn, wenn du das nur für die terminal42 Abhängigkeiten anders machst.

**Comment by jankout** [comment]
@fritzmg das hast du recht. :-)

**Comment by jankout** [comment]
@kmielke Könntest du das bitte anpassen? Sonst kann das niemand ab Contao 4.5 und NC 1.5 nutzen. Das finde ich sehr schade, weil die Erweiterung sehr nützlich ist. 

Schon jetzt danke ich dir für dein Entgegenkommen und deine Antwort und wünsche dir noch einen schönen Tag.
