### ISSUE TITLE
Feature: Kompatibilität mit Rocksolid Slider Pro

### ISSUE THREAD

**Issue by jankout** [kmielke/calendar-extended-bundle#9]
Hallo, 

wäre es bitte möglich, deine tolle Erweiterung für den Rocksolid Slider Pro kompatibel zu machen? Dieser kann die Events darstellen und es wäre toll, wenn ich da auch u.a. die Option "URL Parameter nicht anhängen" haben könnte. 

Der Sliderentwickler hat mir [folgende Sache](http://help.rocksolidthemes.com/discussions/contao/39366-verbesserungsvorschlag-kompatibilitt-mit-anderen-erweiterungen) geschrieben. Es scheint mir erstmal, relativ einfach zu sein. Falls du da Hilfe brauchst, kann ich dich gerne unterstützen.

**Comment by kmielke** [comment]
Hi,
das kannst du recht einfach in einer eigenen kleinen Erweiterung machen. Ich werde vorerst keine Anpassungen in meiner Erweiterung machen, um andere Erweiterungen zu unterstützen.
